---
spring:
  profiles:
    active: dev
---
spring:
    profiles: dev
    datasource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/postgres
      username: futeshi
      password: 
    jpa:
      database: POSTGRESQL
      hibernate:
        ddl-auto: create-drop
---
spring:
    profiles: heroku
    datasource:
      driverClassName: org.postgresql.Driver
    jpa:
      database: POSTGRESQL
      hibernate:
        ddl-auto: none
